# This is workflow checks a given project board every 5th minute and closes all of the issues in the 'done' column.

name: close-done-issues

# Controls when the workflow will run
on: 
  push:
  # schedule: # Workflow will run every 5th minute. 
  #   - cron: "*/5 * * * *"
  # # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  TARGET_PROJECT: TestBacklog


jobs:
  close-done-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Get Project Data
        env: 
          GITHUB_TOKEN: ${{ secrets.PROJECT_ISSUE_CLOSING_PAT }}
          OWNER: ${{ github.repository_owner }}
          PROJECT_NUMBER: 1
        run: |
          projects="$(gh api graphql -f org=$OWNER -F number=$PROJECT_NUMBER -f query='
            query($org: String! $number: Int!) {
              organization(login: $org) {
                projectNext(number: $number) {
                  items (first: 1) {
                    edges {
                      node {
                        title
                        fieldValues (first: 5) {
                          edges {
                            node {
                              projectField {
                                
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          ')"

          echo 'Projects='$projects

          projects="$(gh api graphql -f org=$OWNER -F number=$PROJECT_NUMBER -f query='
            query($org: String! $number: Int!) {
              organization(login: $org) {
                projectNext(number: $number) {
                  fields(first: 5) {
                    edges {
                      node {
                        name
                      }
                    }
                  }
                }
              }
            }
          ')"

           echo 'Projects='$projects


